# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engagement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import engagement_state_pb2 as engagement__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='engagement.proto',
  package='Indriya.Core.Msgs',
  #syntax='proto2',
  serialized_pb=_b('\n\x10\x65ngagement.proto\x12\x11Indriya.Core.Msgs\x1a\x16\x65ngagement_state.proto\"P\n\nEngagement\x12\x0f\n\x07humanId\x18\x01 \x02(\x05\x12\x31\n\x05state\x18\x02 \x01(\x0b\x32\".Indriya.Core.Msgs.EngagementState')
  ,
  dependencies=[engagement__state__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENGAGEMENT = _descriptor.Descriptor(
  name='Engagement',
  full_name='Indriya.Core.Msgs.Engagement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='humanId', full_name='Indriya.Core.Msgs.Engagement.humanId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='Indriya.Core.Msgs.Engagement.state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=143,
)

_ENGAGEMENT.fields_by_name['state'].message_type = engagement__state__pb2._ENGAGEMENTSTATE
DESCRIPTOR.message_types_by_name['Engagement'] = _ENGAGEMENT

Engagement = _reflection.GeneratedProtocolMessageType('Engagement', (_message.Message,), dict(
  DESCRIPTOR = _ENGAGEMENT,
  __module__ = 'engagement_pb2'
  # @@protoc_insertion_point(class_scope:Indriya.Core.Msgs.Engagement)
  ))
_sym_db.RegisterMessage(Engagement)


# @@protoc_insertion_point(module_scope)
